//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleDealerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public int FactoryId { get; set; }
        public string FactoryName { get; set; }
        public string FactoryLocation { get; set; }
        public int Id { get; internal set; }
    }
}
